### PR TITLE
Additional privileges needed for preview

### PR DESCRIPTION
**Pull request by Vlatombe**
* Create/get namespaces
* Get configmap (exposecontroller?)
* Create users/environments

### CODE REVIEW

**Comment by Vlatombe** [comment]
Feels like preview should deserve its own controller. Having to grant 'create namespace' to any build feels too much.

**Comment by rawlingsj** [comment]
> Feels like preview should deserve its own controller. Having to grant 'create namespace' to any build feels too much.

yeah could be something we look at in the future for sure

**Pull request merged**
