### PR TITLE
Add missing privileges to knative-build-bot to perform helm releases

### PR DESCRIPTION
**Pull request by Vlatombe**
* jenkins.io users/releases get/list/watch
* Allow helm to talk to tiller - https://github.com/helm/helm/blob/master/docs/rbac.md#helm-and-role-based-access-control

This should hopefully allow to perform a helm release without using `helm` service account which has cluster admin.

### CODE REVIEW

**Comment by rawlingsj** [comment]
/hold
I'm just about to upgrade and release a new version of knative build so let's hold this until that's merged first.

**Comment by Vlatombe** [comment]
@rawlingsj can you consider this now?

**Comment by rawlingsj** [comment]
great stuff - thanks for being patient

**Comment by Vlatombe** [comment]
@rawlingsj You need to `/hold cancel` I guess

**Comment by rawlingsj** [comment]
/hold cancel
doh

**Pull request merged**
